Added PasswordField to create JPasswordField
CSC207-2023Y-UofT/course-project-hrmanagement pull request #28
Opened 2023-08-04 05:37 UTC by samreengill88

2023-08-04 17:30 UTC, arandaaron04 commented
commits are good, small confusion with checks on git hub otherwise passwords looks good.

2023-08-04 17:31 UTC, OmarRammah approved these changes
This looks good. Does the signup form create an employee class, or are you still working on that?

2023-08-05 14:54 UTC, sarahhe25 requested changes
This looks good! A small confusion with github autocheck should be resolved before merging. Can also add error handling in createPasswordField since the frame can't be null.

2023-08-05 16:43 UTC, daryl-tham approved these changes

2023-08-10 07:23 UTC, closed without merging